export const MY_GETINFO = '/my/MY_GETINFO'
export const MY_ARTICLE_LIST = '/my/MY_ARTICLE_LIST'
export const MY_ARTICLE_LIST_PAGE = '/my/MY_ARTICLE_LIST_PAGE'
export const MY_FORUM_LIST = '/my/MY_FORUM_LIST'
export const MY_FORUM_LIST_PAGE = '/my/MY_FORUM_LIST_PAGE'
export const MY_FAN = '/my/MY_FAN'
export const MY_FOLLOW = '/my/MY_FOLLOW'